sudo: false
language: cpp

compiler:
 - clang
 - gcc

env:
  matrix:
    - CONF=debug   ARCH=x86_64
    - CONF=release ARCH=x86_64
  global:
    - ARCH_FLAGS_x86_64=''
    - secure: "todo"

addons:
  apt:
   sources:
   - ubuntu-sdk-team
   - ubuntu-toolchain-r-test
   - boost-latest
   packages:
   - cmake
   - doxygen
   - valgrind
   - qtdeclarative5-dev
   - libboost-all-dev
   - liblua5.1-dev
   - libsdl1.2-dev
   - libsdl-image1.2-dev
   - libsdl-mixer1.2-dev
   - libsdl-ttf2.0-dev

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi

script:
- mkdir build
- >
  eval "ARCH_FLAGS=\${ARCH_FLAGS_${ARCH}}" ;
  (cd build && cmake
  -DCMAKE_VERBOSE_MAKEFILE=ON
  -DCMAKE_BUILD_TYPE=$CONF
  -DCMAKE_CXX_FLAGS="$ARCH_FLAGS" ..)
- cd build
- make
